#Challenge - Joining on multiple tables
#Write SQL queries to perform the following tasks using the Sakila database:

#List the number of films per category.

SELECT c.name, count( f.film_id ) AS number_films
FROM film_category fc
INNER JOIN film f
ON fc.film_id = f.film_id
INNER JOIN category c
ON c.category_id = fc.category_id
GROUP BY fc.category_id;

#Retrieve the store ID, city, and country for each store.

SELECT store_id, c.city, cntry.country
FROM  store s
JOIN address a
ON s.address_id = a.address_id
JOIN city c
ON a.city_id = c.city_id
JOIN country cntry
on cntry.country_id = c.country_id;

#Calculate the total revenue generated by each store in dollars.

SELECT s.store_ID, sum(amount) as total_revenue
FROM store s
JOIN staff st
ON s.store_id = st.store_id
JOIN payment p
ON p.staff_id = st.staff_id
GROUP BY s.store_id;

#Determine the average running time of films for each category.

SELECT c.name, AVG(f.length) AS avg_length
FROM  category c
JOIN film_category fc
ON c.category_id = fc.category_id
JOIN film f
ON f.film_id = fc.film_id
GROUP BY c.name
ORDER BY avg_length DESC;
